package com.las.timeapp.model;

import jakarta.persistence.*;
import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(name = "measurements")
public class Measurement {
    @Id
    private UUID id; // Generated by mobile app

    @Column(name = "operator_id", nullable = false)
    private UUID operatorId;

    @Column(name = "attraction_id", nullable = false)
    private UUID attractionId;

    @Column(name = "start_time", nullable = false)
    private OffsetDateTime startTime;

    @Column(name = "stop_time")
    private OffsetDateTime stopTime;

    @Column(name = "total_duration_seconds")
    private Integer totalDurationSeconds;

    @Column(name = "sync_status", nullable = false)
    private String syncStatus = "SYNCED";

    @Column(name = "created_at")
    private OffsetDateTime createdAt;

    // Getters and Setters
    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }
    public UUID getOperatorId() { return operatorId; }
    public void setOperatorId(UUID operatorId) { this.operatorId = operatorId; }
    public UUID getAttractionId() { return attractionId; }
    public void setAttractionId(UUID attractionId) { this.attractionId = attractionId; }
    public OffsetDateTime getStartTime() { return startTime; }
    public void setStartTime(OffsetDateTime startTime) { this.startTime = startTime; }
    public OffsetDateTime getStopTime() { return stopTime; }
    public void setStopTime(OffsetDateTime stopTime) { this.stopTime = stopTime; }
    public Integer getTotalDurationSeconds() { return totalDurationSeconds; }
    public void setTotalDurationSeconds(Integer totalDurationSeconds) { this.totalDurationSeconds = totalDurationSeconds; }
    public String getSyncStatus() { return syncStatus; }
    public void setSyncStatus(String syncStatus) { this.syncStatus = syncStatus; }
    public OffsetDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(OffsetDateTime createdAt) { this.createdAt = createdAt; }
}
